### ISSUE TITLE
Unsend command?

### ISSUE THREAD

**Issue by ghost** [Geborgen/moddingsupport#1]
Hey, wondering if you'd consider an unsend command to delete a failed searches embed, just in case it links something completely unrelated when we call for a mod, and then someone installs it anyways causing more issues.

**Comment by Geborgen** [comment]
Arbi is taking a look at implementation

**Comment by Geborgen** [comment]
I've had absolutely zero time for development recently and likely will not for many more weeks. Postponing this

**Comment by Geborgen** [comment]
Implemented via reactions
